export const ADD_MOVIE_TO_WATCH_LIST="ADD_MOVIE_TO_WATCH_LIST";
export const REMOVE_MOVIE_FROM_WATCH_LIST="REMOVE_MOVIE_FROM_WATCH_LIST";
export const ADD_MOVIE_TO_WATCHED="ADD_MOVIE_TO_WATCHED";
export const REMOVE_MOVIE_FROM_WATCHED="REMOVE_MOVIE_FROM_WATCHED";
export const MOVE_TO_WATCH_LIST="MOVE_TO_WATCH_LIST";