export const SliderData=[
  {
    image:"https://rare-gallery.com/uploads/posts/558731-joker-wallpaper.jpeg"
  },
  {
    image:'https://wallpaper.dog/large/10942883.jpg'
  },
  {
    image:'https://wallpaperaccess.com/full/329583.jpg'
  },
  {
    image:'https://wallpaperset.com/w/full/e/a/1/490072.jpg'
  },
  {
    image:'https://m.media-amazon.com/images/M/MV5BOWE1MWE3ZDktOThlZS00ZmRiLWE4ZGEtNWJkMTVlZjdhZDIyXkEyXkFqcGdeQW1pYnJ5YW50._V1_.jpg'
  },
  {
    image:'https://wallpaperaccess.com/full/983569.jpg'
  },
  {
    image:'https://www.teahub.io/photos/full/316-3167731_data-src-black-spiderman-wallpaper-4k.jpg'
  },
  {
    image:'https://images6.alphacoders.com/696/696802.jpg'
  },
  {
    image:'https://wallpapercave.com/wp/wp3132836.jpg'
  },
]